# Generated by Django 4.0.2 on 2022-04-03 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('confirmPassword', models.CharField(max_length=100, null=True)),
                ('firstname', models.CharField(max_length=30, null=True)),
                ('lastname', models.CharField(max_length=30, null=True)),
                ('dateOfBirth', models.DateField(null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('isAdmin', models.BooleanField(default=False)),
                ('isVerified', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('zipcode', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
            ],
        ),
    ]
