# Generated by Django 4.0.2 on 2022-04-29 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0004_user_username_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
