# Generated by Django 4.0.2 on 2022-03-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0005_alter_user_login_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmPassword',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
