# Generated by Django 4.0.2 on 2022-05-01 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0006_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
