# Generated by Django 4.0.2 on 2022-03-01 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0006_user_confirmpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='username',
        ),
    ]
