# Generated by Django 4.0.2 on 2022-04-03 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LocationAPI', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=100, null=True)),
                ('approach', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altitude', models.IntegerField()),
                ('height', models.IntegerField()),
                ('difficulty', models.CharField(max_length=50)),
                ('start_latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('start_longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('finish_latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('finish_longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocationAPI.location')),
            ],
            options={
                'db_table': 'activity',
            },
        ),
    ]
