# Generated by Django 4.0.2 on 2022-05-03 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LocationAPI', '0004_rename_latitude_location_lat_and_more'),
        ('ActivityAPI', '0002_remove_activity_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='LocationAPI.location'),
            preserve_default=False,
        ),
    ]
