# Generated by Django 4.0.2 on 2022-05-03 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LocationAPI', '0004_rename_latitude_location_lat_and_more'),
        ('ActivityAPI', '0004_alter_activity_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocationAPI.location'),
        ),
    ]
