# Generated by Django 4.0.2 on 2022-04-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('altitude', models.IntegerField()),
            ],
            options={
                'db_table': 'location',
            },
        ),
    ]
