# Generated by Django 4.0.2 on 2022-05-01 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocationAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='longitude',
            new_name='lng',
        ),
    ]
