# Generated by Django 4.0.2 on 2022-05-01 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocationAPI', '0002_rename_latitude_location_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='lng',
            new_name='longitude',
        ),
    ]
