# Generated by Django 4.0.2 on 2022-05-01 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocationAPI', '0003_rename_lat_location_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='longitude',
            new_name='lng',
        ),
    ]
