# Generated by Django 4.0.2 on 2022-03-06 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminAPI', '0001_initial'),
        ('LoginAPI', '0008_user_address_user_city_user_isadmin_user_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Review_Images')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('text', models.CharField(max_length=300)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminAPI.activity')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminAPI.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginAPI.user')),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
