# Generated by Django 4.0.2 on 2022-03-08 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAPI', '0008_user_address_user_city_user_isadmin_user_latitude_and_more'),
        ('AdminAPI', '0002_alter_activity_location_delete_post'),
        ('ReviewAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_review', to='AdminAPI.activity'),
        ),
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_review', to='AdminAPI.location'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to='LoginAPI.user'),
        ),
    ]
