# Generated by Django 4.0.2 on 2022-03-06 21:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LoginAPI', '0008_user_address_user_city_user_isadmin_user_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=100, null=True)),
                ('approach', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altitude', models.IntegerField()),
                ('height', models.IntegerField()),
                ('difficulty', models.CharField(max_length=50)),
                ('start_latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('start_longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('finish_latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('finish_longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=100, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('address', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('zipcode', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('altitude', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=300)),
                ('grade', models.CharField(max_length=16)),
                ('photo', models.ImageField(upload_to='Route_Images')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminAPI.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Post_Images')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('likes', models.IntegerField(default=0)),
                ('text', models.CharField(default='', max_length=300)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminAPI.activity')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminAPI.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginAPI.user')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminAPI.location'),
        ),
    ]
